openapi: '3.0.0'
info:
  version: 1.0.0
  title: CardioRightHand API
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /objects:
    get:
      summary: List all objects
      operationId: listObjects
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of objects
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectList'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create object
      operationId: createObject
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /objects/{objectId}:
    get:
      summary: Get object info
      operationId: getObjectById
      parameters:
        - name: objectId
          in: path
          required: true
          description: The id of the object to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectList'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /zones:
    get:
      summary: List all zones
      operationId: listZones
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: A paged array of zones
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zones'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create zone
      operationId: createZone
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Object:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        classification:
          type: string
    ObjectList:
      type: array
      items:
        $ref: '#/components/schemas/Object'
    Zone:
      required:
        - id
        - designation
      properties:
        id:
          type: integer
          format: int64
        designation:
          type: string
        securityLevel:
          type: string
    Zones:
      type: array
      items:
        $ref: '#/components/schemas/Zone'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string